services:
  prospering:
    build:
      context: ./prospering
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - prospering-network
    volumes:
      - ./prospering:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prospering-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  prospering-network:
    driver: bridge

volumes:
  postgres_data:
